/**
 * Formats ScanResult into human-readable markdown or compact text.
 *
 * Two display modes — chosen automatically:
 *   Brief   (issues > 50 or files > 20) — summary + per-engine table + top security issues
 *   Detailed (small / targeted scans)   — per-file, per-issue with source line + fix hint
 */

import type { Issue, ScanResult, Severity, ScanEngine } from "../types.js";

const BRIEF_THRESHOLD_ISSUES = 50;
const BRIEF_THRESHOLD_FILES  = 20;

// Priority order for engines in output (security first, deps second, quality last)
const ENGINE_PRIORITY: Partial<Record<ScanEngine, number>> = {
  "opengrep": 1, "semgrep": 1, "bearer": 2,
  "dependabot": 3, "npm-audit": 4, "pip-audit": 4, "bundler-audit": 4, "cargo-audit": 4,
  "sonar": 5,
  "oxlint": 6, "ruff": 6, "golangci-lint": 6, "rubocop": 6, "pmd": 6, "phpstan": 6,
  "eslint": 7, "tsc": 8, "prettier": 9,
};

export const ENGINE_LABEL: Partial<Record<ScanEngine, string>> = {
  "opengrep":      "Opengrep (security)",
  "semgrep":       "Semgrep (security)",
  "bearer":        "Bearer (data-flow)",
  "oxlint":        "Oxlint (JS/TS quality)",
  "ruff":          "Ruff (Python quality)",
  "golangci-lint": "golangci-lint (Go quality)",
  "rubocop":       "RuboCop (Ruby quality)",
  "pmd":           "PMD (Java quality)",
  "phpstan":       "PHPStan (PHP analysis)",
  "eslint":        "ESLint (project)",
  "tsc":           "TypeScript compiler",
  "prettier":      "Prettier (formatting)",
  "npm-audit":     "npm audit (deps)",
  "pip-audit":     "pip-audit (deps)",
  "bundler-audit": "bundler-audit (deps)",
  "cargo-audit":   "cargo audit (deps)",
  "dependabot":    "Dependabot (deps)",
  "sonar":         "SonarQube/Cloud",
  "ai":            "AI suggestions",
};

const SEVERITY_EMOJI: Record<Severity, string> = { error: "🔴", warning: "🟡", info: "🔵" };
const SEVERITY_LABEL: Record<Severity, string> = { error: "ERROR", warning: "WARNING", info: "INFO" };

// ─── Public API ───────────────────────────────────────────────────────────────

export function toMarkdown(result: ScanResult, context?: string): string {
  if (result.skipped) {
    return `> ⚠️ ${result.skipReason ?? "Scan skipped"}`;
  }

  const { issues, filesScanned } = result;

  if (issues.length === 0) {
    const lines = [
      `## 🔍 argus-ci${context ? ` — ${context}` : ""}`,
      ``,
      `✅ **No issues found** — ${filesScanned} file${filesScanned !== 1 ? "s" : ""} scanned in ${result.durationMs}ms`,
      `_Engines: ${result.engines.map((e) => ENGINE_LABEL[e] ?? e).join(" · ")}_`,
    ];
    const skippedSection = renderSkippedEngines(result.skippedEngines);
    if (skippedSection) lines.push("", skippedSection);
    return lines.join("\n");
  }

  // Choose display mode based on scale.
  // Small targeted scans (≤10 files) always use detailed mode so per-file Sonar
  // findings (which are often MINOR/info severity) are shown and not buried behind
  // the brief top-15 summary.  Brief mode only kicks in for large scans (many files
  // OR many issues AND more than 10 files scanned).
  const isSmallTargetedScan = filesScanned <= 10;
  const useBrief =
    !isSmallTargetedScan &&
    (issues.length > BRIEF_THRESHOLD_ISSUES || filesScanned > BRIEF_THRESHOLD_FILES);

  return useBrief
    ? toBriefMarkdown(result, context)
    : toDetailedMarkdown(result, context);
}

export function toCompact(result: ScanResult): string {
  if (result.skipped) return `SKIPPED: ${result.skipReason}`;
  if (result.issues.length === 0) return `CLEAN — ${result.filesScanned} files scanned`;
  const errors = result.issues.filter((i) => i.severity === "error").length;
  const warns  = result.issues.filter((i) => i.severity === "warning").length;
  return `FOUND ${result.issues.length} issues (${errors} errors, ${warns} warnings) in ${result.filesScanned} files`;
}

export function toPRComment(result: ScanResult, prTitle: string, prUrl: string): string {
  const lines = [
    `## 🔍 argus-ci Security & Quality Scan`,
    `> **PR:** [${prTitle}](${prUrl})`,
    ``,
  ];
  if (result.skipped) {
    lines.push(`> ⚠️ Scan skipped: ${result.skipReason}`);
  } else if (result.issues.length === 0) {
    lines.push(`✅ **No issues found** — ${result.filesScanned} files scanned in ${result.durationMs}ms`);
    lines.push(`_Engines: ${result.engines.map((e) => ENGINE_LABEL[e] ?? e).join(", ")}_`);
  } else {
    lines.push(toMarkdown(result).replace(/^## 🔍 argus-ci[^\n]*\n/, ""));
  }
  lines.push(`\n---\n_Generated by [argus-ci](https://github.com/venkatswaramoyya/argus-ci) · ${new Date().toISOString()}_`);
  return lines.join("\n");
}

// ─── Brief mode (large scans) ─────────────────────────────────────────────────
// Shows: summary stats → per-engine table → top security/dep issues → drill-down tip

function toBriefMarkdown(result: ScanResult, context?: string): string {
  const { issues, filesScanned, durationMs } = result;
  const errors   = issues.filter((i) => i.severity === "error");
  const warnings = issues.filter((i) => i.severity === "warning");
  const lines: string[] = [];

  lines.push(`## 🔍 argus-ci${context ? ` — ${context}` : " scan results"}`, "");

  // ── Summary stats ──────────────────────────────────────────────────────────
  lines.push(
    `| | |`,
    `|---|---|`,
    `| 🔴 Errors   | **${errors.length}** |`,
    `| 🟡 Warnings | **${warnings.length}** |`,
    `| 📁 Files scanned | ${filesScanned} |`,
    `| ⏱ Duration | ${(durationMs / 1000).toFixed(1)}s |`,
    ``
  );

  // ── Per-engine breakdown table ─────────────────────────────────────────────
  const byEngine = groupByEngine(issues);
  const engineEntries = Object.entries(byEngine);
  if (engineEntries.length > 0) {
    lines.push(`### Issues by engine`, ``);
    lines.push(`| Engine | 🔴 Errors | 🟡 Warnings | Top affected files |`);
    lines.push(`|--------|-----------|-------------|-------------------|`);
    for (const [eng, eIssues] of engineEntries) {
      const eErrors = eIssues.filter((i) => i.severity === "error").length;
      const eWarns  = eIssues.filter((i) => i.severity === "warning").length;
      const label   = ENGINE_LABEL[eng as ScanEngine] ?? eng;
      const topFiles = topAffectedFiles(eIssues, 3);
      lines.push(`| ${label} | ${eErrors || "—"} | ${eWarns || "—"} | ${topFiles} |`);
    }
    lines.push("");
  }

  // ── Top actionable issues (security + deps errors, max 15) ─────────────────
  const actionable = issues
    .filter((i) => i.severity === "error")
    .filter((i) => isActionableEngine(i.engine))
    .slice(0, 15);

  if (actionable.length > 0) {
    lines.push(`### 🔴 Top actionable issues`, ``);
    for (const issue of actionable) {
      const label  = ENGINE_LABEL[issue.engine as ScanEngine] ?? issue.engine;
      const loc    = `\`${issue.path}:${issue.line}\``;
      const msg    = issue.message.length > 120
        ? issue.message.slice(0, 117) + "..."
        : issue.message;
      lines.push(`- **[${label}]** ${loc} — ${msg}`);
      if (issue.fixSuggestion) lines.push(`  💡 ${issue.fixSuggestion}`);
    }
    lines.push("");
  }

  // ── Pre-existing debt notice if tsc/eslint dominate ────────────────────────
  const tscCount = byEngine["tsc"]?.length ?? 0;
  const eslintCount = byEngine["eslint"]?.length ?? 0;
  const debtCount   = tscCount + eslintCount;
  if (debtCount > 50) {
    lines.push(
      `> ℹ️ **Note:** ${debtCount.toLocaleString()} of the errors are TypeScript/ESLint issues`,
      `> (${tscCount.toLocaleString()} tsc + ${eslintCount.toLocaleString()} ESLint).`,
      `> These are typically pre-existing debt, not new issues from this scan.`,
      ``
    );
  }

  // ── Drill-down tip ──────────────────────────────────────────────────────────
  lines.push(
    `---`,
    `_To drill into a specific file or folder:_`,
    `\`\`\``,
    `npx argus-ci scan src/auth/login.ts`,
    `npx argus-ci scan src/components/`,
    `\`\`\``,
    `_Or ask your AI agent: "scan the files in context" or "scan src/auth/login.ts"_`
  );

  // ── Skipped passes ──────────────────────────────────────────────────────────
  const skippedSection = renderSkippedEngines(result.skippedEngines);
  if (skippedSection) lines.push("", skippedSection);

  return lines.join("\n");
}

// ─── Detailed mode (targeted scans) ──────────────────────────────────────────
// Shows: per-engine → per-file → per-issue with source line + fix hint

function toDetailedMarkdown(result: ScanResult, context?: string): string {
  const { issues, filesScanned, durationMs } = result;
  const errors   = issues.filter((i) => i.severity === "error");
  const warnings = issues.filter((i) => i.severity === "warning");
  const infos    = issues.filter((i) => i.severity === "info");
  const lines: string[] = [];

  lines.push(`## 🔍 argus-ci${context ? ` — ${context}` : " scan results"}`, "");

  // Summary
  lines.push(
    `| | Count |`,
    `|---|---|`,
    `| 🔴 Errors   | **${errors.length}** |`,
    `| 🟡 Warnings | **${warnings.length}** |`,
    `| 🔵 Info     | ${infos.length} |`,
    `| 📁 Files    | ${filesScanned} |`,
    `| ⏱ Duration  | ${durationMs}ms |`,
    ``
  );

  // Per-engine > per-file > per-issue
  const byEngine = groupByEngine(issues);
  for (const [eng, engineIssues] of Object.entries(byEngine)) {
    const engLabel = ENGINE_LABEL[eng as ScanEngine] ?? eng;
    const eErr = engineIssues.filter((i) => i.severity === "error").length;
    const eWrn = engineIssues.filter((i) => i.severity === "warning").length;
    lines.push(`### ${engLabel} — ${eErr > 0 ? `${eErr} errors` : ""}${eErr > 0 && eWrn > 0 ? ", " : ""}${eWrn > 0 ? `${eWrn} warnings` : ""}`, "");

    const byFile = groupByFile(engineIssues);
    for (const [file, fileIssues] of Object.entries(byFile)) {
      lines.push(`#### 📄 \`${file}\``);
      for (const issue of fileIssues) {
        const emoji = SEVERITY_EMOJI[issue.severity];
        const sLabel = SEVERITY_LABEL[issue.severity];
        lines.push(``, `**${emoji} ${sLabel}** · Line ${issue.line} · \`${issue.ruleId}\``);
        lines.push(`> ${issue.message}`);
        if (issue.sourceLine) {
          lines.push(`\`\`\``, issue.sourceLine, `\`\`\``);
        }
        if (issue.fixSuggestion) lines.push(`💡 **Fix:** ${issue.fixSuggestion}`);
        const meta: string[] = [];
        if (issue.cwe?.length)   meta.push(`CWE: ${issue.cwe.join(", ")}`);
        if (issue.owasp?.length) meta.push(`OWASP: ${issue.owasp.join(", ")}`);
        if (meta.length)         lines.push(`_${meta.join(" · ")}_`);
        if (issue.references?.length) lines.push(`_Refs: ${issue.references.slice(0, 2).join(", ")}_`);
      }
      lines.push("");
    }
  }

  // Skipped passes (e.g. Sonar not configured, tsc skipped for targeted scan)
  const skippedSection = renderSkippedEngines(result.skippedEngines);
  if (skippedSection) lines.push(skippedSection);

  return lines.join("\n");
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function groupByFile(issues: Issue[]): Record<string, Issue[]> {
  const out: Record<string, Issue[]> = {};
  for (const issue of issues) {
    (out[issue.path] ??= []).push(issue);
  }
  for (const list of Object.values(out)) {
    list.sort((a, b) => a.line - b.line);
  }
  return out;
}

function groupByEngine(issues: Issue[]): Record<string, Issue[]> {
  const out: Record<string, Issue[]> = {};
  for (const issue of issues) {
    const eng = issue.engine ?? "unknown";
    (out[eng] ??= []).push(issue);
  }
  // Sort by ENGINE_PRIORITY (security first, quality last)
  return Object.fromEntries(
    Object.entries(out).sort(([a], [b]) => {
      const pa = ENGINE_PRIORITY[a as ScanEngine] ?? 99;
      const pb = ENGINE_PRIORITY[b as ScanEngine] ?? 99;
      if (pa !== pb) return pa - pb;
      // Within same priority, sort by error count desc
      const ae = out[a]!.filter((i) => i.severity === "error").length;
      const be = out[b]!.filter((i) => i.severity === "error").length;
      return be - ae;
    })
  );
}

/** Returns top N most-affected files for a set of issues, as a short string */
function topAffectedFiles(issues: Issue[], max: number): string {
  const counts = new Map<string, number>();
  for (const i of issues) counts.set(i.path, (counts.get(i.path) ?? 0) + 1);
  const sorted = [...counts.entries()].sort((a, b) => b[1] - a[1]);
  const top = sorted.slice(0, max).map(([f]) => basename(f));
  const rest = sorted.length - max;
  return top.join(", ") + (rest > 0 ? ` +${rest} more` : "");
}

function basename(path: string): string {
  return path.split("/").pop() ?? path;
}

/** Security + dep engines are actionable; tsc/eslint debt is not */
function isActionableEngine(engine: ScanEngine | string): boolean {
  const actionable: Array<ScanEngine | string> = [
    "opengrep", "semgrep", "bearer", "sonar",
    "dependabot", "npm-audit", "pip-audit", "bundler-audit", "cargo-audit",
  ];
  return actionable.includes(engine);
}

/**
 * Renders a compact "passes not run" section for the bottom of any scan report.
 * Sonar gets special treatment since its skip reason often contains actionable setup steps.
 */
function renderSkippedEngines(skippedEngines?: Record<string, string>): string | null {
  if (!skippedEngines || Object.keys(skippedEngines).length === 0) return null;

  const lines: string[] = ["---", "**Passes not run:**", ""];

  // Surface Sonar first (most commonly actionable)
  const ORDER = ["sonar", "tsc", "prettier", "bearer", "ai", "dependabot", "npm-audit"];
  const sorted = [
    ...ORDER.filter((e) => e in skippedEngines),
    ...Object.keys(skippedEngines).filter((e) => !ORDER.includes(e)),
  ];

  for (const engine of sorted) {
    const reason = skippedEngines[engine]!;
    const label  = ENGINE_LABEL[engine as ScanEngine] ?? engine;

    if (engine === "sonar") {
      // Sonar skip is almost always actionable — highlight it
      const isNotConfigured = /not set|not configured|run.*configure/i.test(reason);
      if (isNotConfigured) {
        lines.push(
          `- ⚙️ **${label}** — not configured for this repo`,
          `  Run \`npx argus-ci setup --configure\` in this folder to add \`SONAR_PROJECT_KEY\``,
          `  _(project-specific — safe to commit to \`.argus-ci.json\`)_`,
        );
      } else {
        lines.push(`- ⚠️ **${label}** — ${reason}`);
      }
    } else if (engine === "tsc") {
      lines.push(`- ℹ️ **${label}** — ${reason}`);
    } else {
      lines.push(`- ℹ️ **${label}** — ${reason}`);
    }
  }

  return lines.join("\n");
}
