/**
 * Formats ScanResult into human-readable markdown or compact JSON.
 */

import type { Issue, ScanResult, Severity } from "../types.js";

const SEVERITY_EMOJI: Record<Severity, string> = {
  error:   "🔴",
  warning: "🟡",
  info:    "🔵",
};

const SEVERITY_LABEL: Record<Severity, string> = {
  error:   "ERROR",
  warning: "WARNING",
  info:    "INFO",
};

export function toMarkdown(result: ScanResult, context?: string): string {
  if (result.skipped) {
    return `> ⚠️ Scan skipped: ${result.skipReason}`;
  }

  const { issues, filesScanned, durationMs, rulesets } = result;
  const errors   = issues.filter((i) => i.severity === "error");
  const warnings = issues.filter((i) => i.severity === "warning");
  const infos    = issues.filter((i) => i.severity === "info");

  const lines: string[] = [];

  // Header
  if (context) lines.push(`## Semgrep scan — ${context}\n`);
  else         lines.push(`## Semgrep scan results\n`);

  // Summary bar
  if (issues.length === 0) {
    lines.push(`✅ **No issues found** — ${filesScanned} file${filesScanned !== 1 ? "s" : ""} scanned in ${durationMs}ms`);
    lines.push(`\n_Rulesets: ${rulesets.join(", ")}_`);
    return lines.join("\n");
  }

  lines.push(
    `| Severity | Count |`,
    `|----------|-------|`,
    `| 🔴 Error   | ${errors.length}   |`,
    `| 🟡 Warning | ${warnings.length} |`,
    `| 🔵 Info    | ${infos.length}    |`,
    ``,
    `_${filesScanned} file${filesScanned !== 1 ? "s" : ""} scanned · ${durationMs}ms · rulesets: ${rulesets.join(", ")}_`,
    ``
  );

  // Group by file
  const byFile = groupByFile(issues);
  for (const [file, fileIssues] of Object.entries(byFile)) {
    lines.push(`### \`${file}\``);
    for (const issue of fileIssues) {
      const emoji = SEVERITY_EMOJI[issue.severity];
      const label = SEVERITY_LABEL[issue.severity];
      lines.push(`\n**${emoji} ${label}** — Line ${issue.line}`);
      lines.push(`> ${issue.message}`);
      if (issue.sourceLine) {
        lines.push(`\`\`\`\n${issue.sourceLine}\n\`\`\``);
      }
      lines.push(`_Rule: \`${issue.ruleId}\`_`);
      if (issue.cwe?.length)   lines.push(`_CWE: ${issue.cwe.join(", ")}_`);
      if (issue.owasp?.length) lines.push(`_OWASP: ${issue.owasp.join(", ")}_`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

export function toCompact(result: ScanResult): string {
  if (result.skipped) return `SKIPPED: ${result.skipReason}`;
  if (result.issues.length === 0) return `CLEAN — ${result.filesScanned} files scanned`;

  const errors = result.issues.filter((i) => i.severity === "error").length;
  const warns  = result.issues.filter((i) => i.severity === "warning").length;
  return `FOUND ${result.issues.length} issues (${errors} errors, ${warns} warnings) in ${result.filesScanned} files`;
}

export function toPRComment(result: ScanResult, prTitle: string, prUrl: string): string {
  const lines: string[] = [
    `## 🔍 Semgrep Quality Scan`,
    `> **PR:** [${prTitle}](${prUrl})`,
    ``,
  ];

  if (result.skipped) {
    lines.push(`> ⚠️ Scan skipped: ${result.skipReason}`);
    return lines.join("\n");
  }

  if (result.issues.length === 0) {
    lines.push(`✅ **No issues found** — ${result.filesScanned} files scanned in ${result.durationMs}ms`);
    lines.push(`\n_Rulesets: ${result.rulesets.join(", ")}_`);
    return lines.join("\n");
  }

  // Append full markdown report
  lines.push(toMarkdown(result).replace(/^## Semgrep scan results\n/, ""));
  lines.push(`\n---\n_Generated by [argus-ci](https://github.com) · ${new Date().toISOString()}_`);
  return lines.join("\n");
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function groupByFile(issues: Issue[]): Record<string, Issue[]> {
  const result: Record<string, Issue[]> = {};
  for (const issue of issues) {
    (result[issue.path] ??= []).push(issue);
  }
  // Sort each file's issues by line number
  for (const issues of Object.values(result)) {
    issues.sort((a, b) => a.line - b.line);
  }
  return result;
}
